# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f916603696efbf1b479603e5ec771b433436666102230c3d068d15bcc690cb5885bcc05bffdac72787880e7e42706bd8204284e39cab8b30dcb09444e4efaf7f

test:
  secret_key_base: 48d9cfefb7f1999e169a36aa00e9457b54a3e7d31a88ce939c847b5604ccda13a9335ff85d2f5d3d34ce21888aebd461469a0799fd63b28b28796e375ebf8001

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
